apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: nawedanjum/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: JWT_LIFE
              valueFrom:
                secretKeyRef:
                  name: jwt-life
                  key: JWT_LIFE
            - name: REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: refresh-secret
                  key: REFRESH_KEY
            - name: REFRESH_LIFE
              valueFrom:
                secretKeyRef:
                  name: refresh-life
                  key: REFRESH_LIFE
            - name: MONGODB_URI_AUTH
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-issuer
                  key: JWT_ISSUER
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
