name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t nawedanjum/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push nawedanjum/tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save fe1f4c2e-05b2-4adf-b9bc-df0c496110e4
      - run: kubectl rollout restart deployment tickets-depl
